### ISSUE TITLE
Диаграмма структуры данных

### ISSUE THREAD

**Issue by MikeSafonov** [MikeSafonov/operator-bot#1]
Необходимо нарисовать диаграмму структуры данных для будущего бота. 
Нам необходимо хранить следующую информацию:
- пользователи бота, которые будут заступать на дежурства. кроме идентификатора телеграмм, предлагаю еще хранить ФИО и некий статус.
- расписание дежурств (кто и когда дежурил)
- внешние пользователи (список тех, кто будет обращаться в бот за консультацией). Для них, как и для дежурных, необходимо хранить также ФИО.

Воспользоваться предлагаю [dbdiagram.io](https://dbdiagram.io/home). В репозиторий в папку `docs/db` можно будет приложить код диаграммы.

**Comment by gagrim1** [comment]
Увидел

**Comment by MikeSafonov** [comment]
👍
