### ISSUE TITLE
Учет красных дней календаря и рабочих дней

### ISSUE THREAD

**Issue by MikeSafonov** [MikeSafonov/operator-bot#26]
Необходимо добавить две таблицы в БД в которых будут храниться:
- список дополнительных выходных 
- список дополнительных рабочих дней

Эти дни необходимо учитывать в процесс определения дежурного. Соответственно, если день в списке выходных, то для него дежурный не назначается, а если день рабочий, то назначается.

Кроме этого, необходимо реализовать HTTP API для управления этими справочниками (добавить, удалить, получить с учетом постраничного вывода (Pageable))

**Comment by gagrim1** [comment]
Принял

**Comment by MikeSafonov** [comment]
gh-
